runtime: python39
entrypoint: gunicorn -b :$PORT etkinlik_takas.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "etkinlik_takas.settings"
  GOOGLE_CLOUD_PROJECT: "etkinlik-takas"

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /media
  static_dir: media/
  secure: always

- url: /.*
  script: auto
  secure: always 