# Generated by Django 5.2 on 2025-05-02 19:00

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resim_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resim',
            field=models.ImageField(upload_to=tickets.models.upload_to_firebase),
        ),
    ]
